apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-gitops-pipeline
  namespace: argocd          # Directs the declaration to the ArgoCD controller space
spec:
  project: default
  source:
    repoURL: 'https://github.com/georgelza/gitops-pipeline.git'
    targetRevision: main
    path: k8s                 # Instructs ArgoCD to track your manifests inside the k8s folder
  destination:
    server: 'https://kubernetes.default.svc' # Instructs it to deploy to the local cluster
    namespace: app           # Directs deployment straight into your isolated 'app' namespace
  syncPolicy:
    automated:
      prune: true            # Automatically deletes K8s resources if you remove them from Git
      selfHeal: true         # Overwrites manual cluster overrides to keep Git as the single source of truth